packaging_format = 2

id = "invited"
name = "InviteD"
description.en = "Invite management system for YunoHost"
#description.fr = ""

version = "0.0.1"

maintainers = ["John Hackett"]

[upstream]
license = "GPLv2"
website = "https://github.com/jmthackett/invited_ynh"
code = "https://github.com/jmthackett/invited_ynh"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.target_permissions] # what group do we add users to?
    ask.en = "What permissions should the new users have? (Create a new group to give users more limited permissions!)"
    type = "group"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        # This will pre-fetch the asset which can then be deployed during the install/upgrade scripts with :
        #    ynh_setup_source --dest_dir="$install_dir"
        # You can also define other assets than "main" and add --source_id="foobar" in the previous command
        url = "https://github.com/jmthackett/invited_ynh/archive/refs/tags/0.0.3.zip"
        sha256 = "d913c66f99270e8a0baaec4f2b317639d3b7c8b5279b24fad2d1bd65f8ee59ee"

        # These infos are used by https://github.com/YunoHost/apps/blob/master/tools/autoupdate_app_sources/autoupdate_app_sources.py
        # to auto-update the previous asset urls and sha256sum + manifest version
        # assuming the upstream's code repo is on github and relies on tags or releases
        # See the 'sources' resource documentation for more details

        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
