packaging_format = 2

id = "invited"
name = "InviteD"
description.en = "Invite management system for YunoHost"
#description.fr = ""

version = "0.0.1"

maintainers = ["John Hackett"]

[upstream]
license = "GPLv2"
website = "https://github.com/jmthackett/yunohost_invited"
code = "https://github.com/jmthackett/yunohost_invited"

[integration]
yunohost = ">= 11.1.15"
architectures = "all"
multi_instance = true
ldap = false
sso = true
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.target_permissions] # what group do we add users to?
    ask.en = "What permissions should the new users have? (Create a new group to give users more limited permissions!)"
    type = "group"
    
    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]

    [resources.sources]

        [resources.sources.main]
        url = ""
        sha256 = ""
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
